version: '3.9'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../reactApp:/usr/src/app
    command: sh -c "cd reactsample && npm start"
    ports:
      - "3000:3000"
    tty: true